name: savia
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  awesome_notifications: ^0.7.4+1
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.1.1
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.6
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_slidable: ^2.0.0
  gallery_saver: ^2.3.2
  giphy_picker: ^3.0.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.0.1
  http: ^0.13.5
  image_picker: ^0.8.6+4
  intl_phone_field: ^3.1.0
  line_icons: ^2.0.1
  lottie: ^2.3.0
  photo_view: ^0.14.0
  pinput: ^2.2.31
  zego_uikit_prebuilt_call: ^2.1.3
  after_layout: ^1.2.0
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: ShantellSans-Light
      fonts:
        - asset: assets/fonts/ShantellSans-Light.ttf
    - family: ShantellSans-Regular
      fonts:
        - asset: assets/fonts/ShantellSans-Regular.ttf
    - family: Mulish-Regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
